using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Networking;
using UnityEngine.UI;
//
// [Serializable]
// public class RoomRoomListInfo() 
// {
//     public string roomName;
//     public float roomReturn;
//     public int roomMaxPlayer;
// }

public class RoomSetting : MonoBehaviour
{
    //μΈν’‹ν•„λ“
    public InputField roomNameInput;
    public InputField roomReturnInput;
    public InputField roomMaxPlayerInput;
    //
    // public void OnClickRoomCreate()
    // {
    //     SaveRoomInfo roomdata = new SaveRoomInfo();
    //     roomdata.roomName = roomNameInput.text;
    //     roomdata.roomReturn = float.Parse(roomReturnInput.text);
    //     roomdata.roomMaxPlayer = int.Parse(roomMaxPlayerInput.text);
    // }

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
